config/routes.rb
Rails.application.routes.draw do
    
    
    resources :messages
    get 'pages/home'
    get 'pages/about'
    get 'pages/commercial'
    get 'pages/residential'
    

   root 'pages#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
    validates_presence_of (:email)
    validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def show
        @contact = Message.find(params[:id])
    end
    
    def new
       @contact = Message.new
    end
    
    def create
      @contact = Message.new(contact_params)
      if @contact.save
          redirect_to :action => 'show'
      else
      render :action => 'new'
      end
          
    end
    
    
    private
    
      def contact_params
          params.require(:user).permit(:name,:email,:inquiry)
      end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
    def show
        if flash[:redirect] == 'form_submitted'
          @message = Message.find(params[:id])
        else
          redirect_to pages_home_path
        end
    end
    
    def new
        @message = Message.new
    end
    
    def create
        @message = Message.new(message_params)
        if @message.save
            ContactMailer.contact(@message).deliver
            ContactMailer.mail_alert(@message).deliver
            flash[:redirect] = 'form_submitted'
            redirect_to @message
        else
        render 'new'
        
        end
        
    end
    
    private
    
      def message_params
          params.require(:message).permit(:name,:email,:inquiry)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def residential
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>© 2016 Nomadic Inc.</p>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomadic</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>

<%= yield %>
<%= render 'layouts/footer' %>
 

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
 
  
  <div class="field form-group">
    <%= f.label :name, :style => "display:block;" %> 
    <%= f.text_field :name %>
  </div>
  
  <% if @message.errors.any? %>
  <div id="error_explanation">
    <!-- <h2> <%=pluralize(@message.errors.count, "error") %> 
    prohibited this article from being saved:</h2> -->
      <ul style="text-align: left; margin: 0 auto; width: 200px; color: red; padding-bottom: 10px; margin-top: -10px;"> 
      <% @message.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
      </ul>
  </div>
  <% end %>
  
  <div class="field form-group">
    <%= f.label :email, 'Email *', :style => "display: block;" %>
    <%= f.text_field :email %>
  </div>
  
 
  
  <div class="field form-group">
    <%= f.label :inquiry, :style => "display: block;" %>
    <%= f.text_area :inquiry, :size => "x3", :style => "overflow: auto;" %> 
  </div>  
  
  <div class="actions submit_button">
    <%= f.submit "Send Message" %>
  </div>
<% end %>

app/views/messages/new.html.erb
<body>

<div class="wrapper">

 <nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/pages/home"><img src="/assets/NomadicLogo2.png" style="width: 200px; height: 90px; margin-top:-38px; margin-left:-20px;"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", pages_home_path %></li>
        <li><%= link_to "ABOUT", pages_about_path %></li>
        <li><%= link_to "CONTACT", new_message_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">SERVICES
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Commercial" %></li>
            <li><%= link_to "Residential", pages_residential_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
 

 

  
 <div class="container-fluid text-center contact_wrapper" style="padding-top: 20px;">
   <div class="row contact_1">
   	  <img src="/assets/ipad2.png">
   	  <div class="caption">
        <h3> Contact Form </h3> 


  		<%= render 'form' %>
	  </div>
    </div>
  </div>
</div>  
  <script>
    $(function() {
  return $('.submit_button').click(function() {
    var answer;
    return answer = confirm('Are you sure?');
  });
});

if (answer) {
  alert('Message Sent!');
} else {
  e.preventDefault();
}

  </script>

</body>

app/views/messages/show.html.erb
<div class ="show"> 
<p>
  <strong>Name:</strong>
  <%= @message.name %>
</p>  

<p>
  <strong>E-mail adress:</strong>
  <%= @message.email %>
</p>  

<p>
  <strong>Inquiry:</strong>
  <%= @message.inquiry %>
</p>  

</div>

app/views/pages/about.html.erb
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">
  	  
<div class="wrapper_about">
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/pages/home"><img src="/assets/NomadicLogo2.png" style="width: 200px; height: 90px; margin-top:-38px; margin-left:-20px;"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", pages_home_path %></li>
        <li><%= link_to "ABOUT", pages_about_path %></li>
         <li><%= link_to "CONTACT", new_message_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">SERVICES
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Commercial" %></li>
            <li><%= link_to "Residential", pages_residential_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="row_about_1" style="display: inline-block;">
	<div class="col-sm-6 col-xs-12 about_pict" style="padding-top: 50px;"> 
        <img src="https://app.wishloop.com/builder/be_assets/img/predefined_images/business-man.png" alt="logo front" />
	</div> 
	
	<div class="col-sm-6 text-center about_col_2">
      <h2>About Us</h2>
      <img src="http://www.clker.com/cliparts/v/i/H/4/5/A/swirl-1-hi.png">
       <p style="padding-top: 20px;"> Nomadic Inc. was founded by Nick Sella in 2005, with the goal of providing fast and reliable technical support to the city of Tuscaloosa. 
       Our company supports both individuals with computer issues as well as businesses needing someone to maintain their networks and office computers. With almost 30 years of experience,
       Nick has worked on projects for large corporations and has always managed to solve his customers' technical problems quickly and to their satisfaction.     </p>
    </div> 
</div>
</div>
<div class="footer" style="padding-top: 0px;">
<p> © 2016 Nomadic Inc. </p>
</div>

</body>

   <!-- <script>
  	    $(document).ready(function(){
  		  $('#card').flip({
  		  trigger: 'click',
  		  trigger: 'hover',
  		  })
  		  });
	</script> ->

app/views/pages/commercial.html.erb
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/pages/home"><img src="/assets/NomadicLogo2.png" style="width: 200px; height: 90px; margin-top:-38px; margin-left:-20px;"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", pages_home_path %></li>
        <li><%= link_to "ABOUT", pages_about_path %></li>
         <li><%= link_to "CONTACT", new_message_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">SERVICES
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Commercial</a></li>
            <li><a href="#">Residentail</a></li>
          </ul>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

  <div class="row_com_1 container-full" style="margin: 0 auto; display: inline-block; position: relative;">
	<div>
	  <img src="http://www.a1systems.net/img/0129/029.jpg?sitetimestamp=635840617430000000" style="width: 100%; height: auto; display: block; -webkit-filter: contrast(60%);"> 
    </div>
    <div>
	  <p> Residential Technical Support</p>
	</div>
  </div>


 <div class="row_com_2 container-fluid">
   <div class="col-sm-6 col_com" style="text-align: center;">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%);">&#xE2BD</i>
     <h3 style=" letter-spacing: normal; color: #777;"> Cloud Support</h3>
     <p> We will setup cloud support on your devices so that all of your data and resources will be backed up. 
     Clouds also let you easily share information among your devices.
   </div>
   <div class="col-sm-6 text-center col_com">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%);">&#xE30A</i>
     <h3 style=" letter-spacing: normal; color: #777;"> PCS and MACS</h3>
     <p>Whether you need help setting up a new computer or simply want a tune-up to optimize your computer's performance, we have you covered. </p>
   </div>
 </div>
 
 <div class="row_com_2 container-fluid"> 
   <div class="col-sm-6 text-center col_com">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%);">&#xE32A</i>
     <h3 style=" letter-spacing: normal; color: #777;"> Virus Removal and Firewall Setup</h3>
     <p> Don't let a virus ruin your computer. We will backup all of your computer's data and kill any viruses. Then,
     install powerful virus protection that will keep your computer safe. 
   </div>
   <div class="col-sm-6 text-center col_com">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%);">&#xE1DB</i>
     <h3 style=" letter-spacing: normal; color: #777;"> Data Recovery</h3>
       <p> Have you lost acces to important files or images? Hard drives, like any other electronic device, will eventually fail. 
       We will recover all of your computer's data and help you setup backup storage so that you will not have to deal with data loss again. </p>
   </div>
 </div>

</body> 

app/views/pages/home.html.erb
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">
  	  

<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/pages/home"><img src="/assets/NomadicLogo2.png" style="width: 200px; height: 90px; margin-top:-38px; margin-left:-20px;"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", pages_home_path %></li>
        <li><%= link_to "ABOUT", pages_about_path %></li>
        <li><%= link_to "CONTACT", new_message_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">SERVICES
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Commercial" %></li>
            <li><%= link_to "Residential", pages_residential_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/assets/Busy_dark.jpg">
        <div class="carousel-caption">
          <h3>Technical Solutions on the Move</h3> 
          <A HREF="#learn_more"><button class="Carousel_Button">Learn More</button></A>
        </div>      
      </div>

      <div class="item Residential">
        <img src="/assets/Res.jpg"> 
        <div class="carousel-caption">
          <h3>Quality Service For Residential Customers</h3>
          <a href="/pages/residential"><button class="Carousel_Button">Click Here</button></a>
        </div>      
      </div>
    
      <div class="item Residential">
        <img src="/assets/Business.jpg">
        <div class="carousel-caption">
          <h3>Premier on-site Service for Businesses</h3>
          <button class="Carousel_Button">Click Here</button>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a> 
</div> 

   	  
<!-- </div> -->

<div class="container-fluid">   
	<A NAME="learn_more"><div class="row1 text-center"></A>
	  <div class="col-lg-4">
	    <img src="/assets/Bulb.jpg" style="height: 98px" class="Experience">
	    <h3 class="Logo_Header">25 Years of Experience</h3>
	    <p class="Logo_P"> With a long history of providing IT support to Tuscaloosa, 
	    we have seen almost every problem and know how to fix it. </p>
	  </div>
	  <div class="col-lg-4">
	    <img src="/assets/Car.jpg"> 
	    <h3 class="Logo_Header">We Come to You</h3>
	    <p class="Logo_P">Busy schedule? We provide in-home and in-office computer assistance to meet your needs.</p>
	  </div>
	  <div class="col-lg-4">
	    <img src="/assets/Phone.jpg">
	    <h3 class="Logo_Header"> Need Assistance? </h3>
	    <p><strong>Location:</strong> Tuscaloosa, AL 35404 <br> 
	    <strong>Phone:</strong> 205-799-1667  <br> 
	    <strong>Email:</strong> nsella@comcast.net</p>
	  </div>
	</div>
</div>

 <div class="container-full">
  <div class="row2_home">
    <div class="col-sm-6 text-center" style="margin-bottom:50px;">
     <h2> Serving Our Community Since 2005 </h2>
     <p> We always strive to build long-term relationships with our clients. 
     Our philosophy of customer satisfaction and fast service has allowed our business to grow substantially.
     We put our customers first, and will make sure that your technical problem is fixed the first time.  </p>
    </div> 
    <div class="col-sm-6 row2_img"> 
     <img src="/assets/Network2.png">
    </div>  
  </div>
 <!--<div class="push">
 </div> -->
 </div>
 
<!--<div class="footer" style="background-color: #003399; -webkit-filter: brightness(90%); text-align: center; color: white;">
   <p>© 2016 Nomadic Inc.</p>
</div> -->
  
<!-- Calling jquery first -->
<script language="JavaScript" type="text/javascript" src="scripts/jquery.js"></script>
<script language="JavaScript" type="text/javascript" src="scripts/bootstrap.min.js"></script>
  <!-- Carousel -->
<script language="JavaScript" type="text/javascript">
  $(document).ready(function(){
    $('.carousel').carousel({
      interval: 3000
    })
  });    
</script>  
  
</body>

app/views/pages/residential.html.erb
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/pages/home"><img src="/assets/NomadicLogo2.png" style="width: 200px; height: 90px; margin-top:-38px; margin-left:-20px;"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", pages_home_path %></li>
        <li><%= link_to "ABOUT", pages_about_path %></li>
         <li><%= link_to "CONTACT", new_message_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">SERVICES
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Commercial" %></li>
            <li><%= link_to "Residential", pages_residential_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <div class="row_com_1 container-full" style="margin: 0 auto; display: inline-block; position: relative;">
	<div>
	  <img class="com_photo" src="/assets/Residential_img.jpg"> 
    </div>
    <div>
	  <p> Residential Technical Support</p>
	</div>
  </div>


 <div class="row_com_2 container-fluid">
   <div class="col-sm-6 col_com" style="text-align: center;">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%); filter: brightness(90%);">&#xE2BD</i>
     <h3 style=" letter-spacing: normal; color: #777;"> Cloud Support</h3>
     <p> We will setup cloud support on your devices so that all of your data and resources will be backed up. 
     Clouds also let you easily share information among your devices.
   </div>
   <div class="col-sm-6 text-center col_com">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%); filter: brightness(90%);">&#xE30A</i>
     <h3 style=" letter-spacing: normal; color: #777;"> PCs and Macs</h3>
     <p>Whether you need help setting up a new computer or simply want a tune-up to optimize your computer's performance, we have you covered. </p>
   </div>
 </div>
 
 <div class="row_com_2 container-fluid"> 
   <div class="col-sm-6 text-center col_com">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%); filter: brightness(90%);">&#xE32A</i>
     <h3 style=" letter-spacing: normal; color: #777;"> Virus Removal and Firewall Setup</h3>
     <p> Don't let a virus ruin your computer. We will backup all of your computer's data and kill any viruses. Then,
     install powerful virus protection that will keep your computer safe. 
   </div>
   <div class="col-sm-6 text-center col_com">
     <i class="material-icons" style="font-size:60px;color:#003399; -webkit-filter: brightness(90%); filter: brightness(90%);">&#xE1DB</i>
     <h3 style=" letter-spacing: normal; color: #777;"> Data Recovery</h3>
       <p> Have you lost acces to important files or images? Hard drives, like any other electronic device, will eventually fail. 
       We will recover all of your computer's data and help you setup backup storage so that you will not have to deal with data loss again. </p>
   </div>
 </div>

 <div class="push">
 </div>
 
<script>


if (document.documentElement.clientWidth > 760) {

    $(function() {
    var listHeight = (($('.row_com_1 img').height()-$('.row_com_1 p').height())/2)+($('.row_com_1 p').height())/2;
    //$('.height').append('<p>' + listHeight + 'px<p>'); 
    window.onscroll = function() {
    if ($(window).scrollTop() <= listHeight){
            jQuery('.row_com_1 p').css({position: 'fixed'});
        }
    else {
        	jQuery('.row_com_1 p').css({position: 'absolute'});
        }
  	}
  });

  $(window).load(function() {
	var listHeight = (($('.row_com_1 img').height()-$('.row_com_1 p').height())/2)+$('.row_com_1 p').height();
        if ($(window).scrollTop() <= listHeight){
            jQuery('.row_com_1 p').css({position: 'fixed'});
        }
        else {
        	jQuery('.row_com_1 p').css({position: 'absolute'});
        }
    });
    
   $(window).load(function() {
    var listHeight = (($('.row_com_1 img').height()-$('.row_com_1 p').height())/2);
    //$('.height').append('<p>' + listHeight + 'px<p>'); 
    window.onscroll = function() {
    if ($(window).scrollTop() <= listHeight){
            jQuery('.row_com_1 p').css({position: 'fixed'});
        }
    else {
        	jQuery('.row_com_1 p').css({position: 'absolute'});
        }
  	}
  });
  

  
   $(window).resize(function() {
	var listHeight = ((($('.row_com_1 img').height()-$('.row_com_1 p').height())/2)+$('.row_com_1 p').height())/1.2;
	//$('.height').append('<p>' + listHeight + 'px<p>'); 
	window.onscroll = function() {
        if ($(window).scrollTop() <= listHeight){
            jQuery('.row_com_1 p').css({position: 'fixed'});
        }
        else {
        	jQuery('.row_com_1 p').css({position: 'absolute'});
        }
    }
});

}

</script>  

</body> 

 <script> 
/*
 jQuery(document).ready(function(){
 	var $tall = $('.row_com_1 p').width();
    window.onscroll = function() {
        if ($(window).scrollTop() <= $tall){
            jQuery('.row_com_1 p').css({position: 'fixed'});
        }
        else {
        	jQuery('.row_com_1 p').css({position: 'absolute'});
        }
    }
});  

$(window).load(function() {
	var $height = $('.row_com_1 p').height();
        if ($(window).scrollTop() <= 200){
            jQuery('.row_com_1 p').css({position: 'fixed'});
        }
        else {
        	jQuery('.row_com_1 p').css({position: 'absolute'});
        }
    });


*/

 </script> 

  <script>
$(document).ready(function() {
  centerContent();
  });
$(window).load(function()
{
	centerContent();
});

$(window).resize(function()
{
	centerContent();
});




function centerContent()
{
	var container = $('.row_com_1 img');
	var content = $('.row_com_1 p');
	content.css("left", (container.width()-content.width())/2);
	content.css("top", (container.height()-content.height()+$('.navbar').height())/2);
}
  </script>  